### ISSUE TITLE
Guice Annotation Introspection doesn't observer JacksonInject.useInput values

### ISSUE THREAD

**Issue by josephlbarnett** [FasterXML/jackson-modules-base#134]
When trying to do something similar to https://github.com/FasterXML/jackson-databind/issues/962 while using the jackson guice module to provide injectable values from the guice bindings, setting the `useInput=OptBoolean.FALSE` property is ineffective.  It appears that https://github.com/FasterXML/jackson-modules-base/blob/2.12/guice/src/main/java/com/fasterxml/jackson/module/guice/GuiceAnnotationIntrospector.java#L22 always constructs a JacksonInject.Value with `useInput=null`, so there is no way to tell jackson the injected value should be "inject-only".

**Comment by josephlbarnett** [comment]
Have attempted to look at this here: https://github.com/FasterXML/jackson-modules-base/compare/2.12...josephlbarnett:guice-annotation-use-input

This allows me to avoid the injection failure from https://github.com/FasterXML/jackson-databind/issues/962 by setting `useInput=OptBoolean.FALSE`, but as seen in the attached test that fails, it appears that the injected value is always used even in the default/TRUE cases?  For my specific use case that's ok, but seems unexpected / like I'm missing something about how this should work?

**Comment by cowtowncoder** [comment]
If suggesting this change, it probably would need to be a configurable setting just to make sure.

Ideally `AnnotationIntrospector` here should not really have to do this processing; it should usually be up to `AnnotationIntrospectorPair.java` to merge possible values.

Come to think it now, it looks like implementation there is the problem:

```
    public JacksonInject.Value findInjectableValue(AnnotatedMember m) {
        JacksonInject.Value r = _primary.findInjectableValue(m);
        return (r == null) ? _secondary.findInjectableValue(m) : r;
    }
```

since it probably should be doing this merging...

Would you be interested in trying a PR for `jackson-databind` (branch 2.12) for that?

**Comment by josephlbarnett** [comment]
ah the injected value issue appears to be similar if not the same as https://github.com/FasterXML/jackson-databind/issues/2678 

I can see if a change to AnnotationIntrospectorPair to merge id/useInputs from primary/secondary would help with the https://github.com/FasterXML/jackson-databind/issues/962 part of the problem -- should it be something along the lines of "use the primary value, but if useInput is null/default, merge primary id with secondary useInput"?

**Comment by cowtowncoder** [comment]
@josephlbarnett yes, merging should only "fill in the blanks", and `OptBoolean` is designed to allow "not defined" (instead of `boolean` property).
