### ISSUE TITLE
Copyright Notice in License is missing

### ISSUE THREAD

**Issue by divyank-vwits** [FasterXML/jackson-modules-base#139]
For companies that use this library, it is important to understand who is the copyright holder.
In the license file that is attached, the copyright holder is not clearly stated but it is still kept as the template value.

It would be great if you could add the name(s) of the copyright holder such that the legal situation gets clarified properly.

**Comment by philwebb** [comment]
@divyank-vwits I see you've opened this issue in many repositories. I suspect most will consider the issue invalid for the [reasons given here](https://github.com/spring-projects/spring-boot/issues/27021). In the future, you might want to wait for a response before opening duplicate issues.

**Comment by cowtowncoder** [comment]
One thing that is challenging in adding specific copyright information is that although there is typically one main contributor (lead author) for all components -- and in most cases that would be me -- there are also many contributors.
Authors retain their copyright to the contributions as per CLA we use (see https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf and matching CCLA).

So if anyone can suggest a suitable copyright notice to use for such cases (one where it is not practical to even try to enumerate every contributor), that would be useful.

This is also something that would be better discussed on the developer mailing list:

https://groups.google.com/g/jackson-dev
