### ISSUE TITLE
Contributing new module?

### ISSUE THREAD

**Issue by chrylis** [FasterXML/jackson-modules-base#148]
I am writing a library that handles mail and have decided to adopt the brand-new Jakarta namespace. I need to serdes `jakarta.mail.internet.InternetAddress` in the Obvious Format and have written a Jackson module that does this. Since `InternetAddress` is part of the JakartaEE standard library, would contributing the module be on-topic for either this project or another one that I'm not aware of?

**Comment by cowtowncoder** [comment]
This sounds like a datatype library, so I think the closest match would be:

    https://github.com/FasterXML/jackson-datatypes-misc/

and yes I think that'd be in-scope. Over time structure of multi-module repos has changed and there's always possibility of reorgs, but without knowing much more that repo could work well.
Depending on timing it might even get into 2.13 released -- but if not, 2.14 would be fine (and sometimes we do "dark launches", adding unofficially in one of patches of earlier minor version, as this helps getting more testing).
