### ISSUE TITLE
jakarta-xmlbind/src/moditect/module-info.java is invalid

### ISSUE THREAD

**Issue by agavrilov76** [FasterXML/jackson-modules-base#161]
This `jakarta-xmlbind/src/moditect/module-info.java` file refers to a non existing class `com.fasterxml.jackson.module.jakarta.xmlbind.JakartaXmlBindModule` which breaks service module loading for modular Java applications.
 
`JakartaXmlBindModule` should probably be `JakartaXmlBindAnnotationModule`

**Comment by tatu-at-datastax** [comment]
Which version?

**Comment by agavrilov76** [comment]
> Which version?

2.13.0

I was upgrading my modular application from version 2.12.3 to 2.13.0 and got an error while finding registered modules

**Comment by cowtowncoder** [comment]
Ugh. First of all: THANK YOU for reporting this issue. I will fix it; just wish I had an easy way to test it (there is "jackson-integration-tests" and another repo that supposedly could have a test, but cannot quite test from within base repo unit tests, with Java 8 baseline).

... and this also makes me sad wrt community involvement, Release Candidates. No one noticed this at all during 2 month period during which RCs were published. :-(
Granted it is a new module but... also one that was requested by many who wanted to move to the new "Jakarta" stack of things.

**Comment by GedMarc** [comment]
I'm busy updating the jdk11-compat-tests library with the module to catch these :) 
Never saw this come in sorry guys!

**Comment by cowtowncoder** [comment]
@GedMarc no problem: without your help we'd had no tests :)

Timing is bit unfortunate as I JUST released 2.13.1 so it'll take a while to get to 2.13.2.

**Comment by agavrilov76** [comment]
Thank you for prompt response.

I'm going to switch the new version once it is available and test it out in the Java modular world
