### ISSUE TITLE
Documentation: ObjectMapper.addModule() does not exist

### ISSUE THREAD

**Issue by numeralnathan** [FasterXML/jackson-modules-base#168]
This page says to call `addModule()`.  However, `ObjectMapper.addModule()` does not exist.  I think it should say `registerModule()`.

https://github.com/FasterXML/jackson-modules-base/tree/master/afterburner

**Comment by cowtowncoder** [comment]
Please re-read the code example... you did miss a small detail. :)

(correct, mapper has no such method but that's not what code sample show)

**Comment by numeralnathan** [comment]
Oh, thank you.  I saw `ObjectMapper` and thought I was working with it.

**Comment by cowtowncoder** [comment]
No problem, I can see how that can happen. :)
And there definitely are cases where READMEs are out of date or have typos. So I rather get occasional false positive than miss actual fixes.

There are also sometimes problems between Jackson 3.0 (future major version) and 2.x; APIs differ a bit.
