### ISSUE TITLE
`jackson-module-jakarta-xmlbind-annotations` should use a Jakarta namespaced Activation API

### ISSUE THREAD

**Issue by jamezp** [FasterXML/jackson-modules-base#175]
Currently the `com.fasterxml.jackson.module:jackson-module-jakarta-xmlbind-annotations` uses uses `jakarta.activation:jakarta.activation-api:1.2.2`. This is a `javax` namespaced API. The version 2.0.1 should be used to align with `jakarta.xml.bind:jakarta.xml.bind-api:3.0.1`.

If this can also be backported to 2.13 please let me know as this is a blocker for RESTEasy and WildFly to be able to upgrade.

**Comment by cowtowncoder** [comment]
Ugh. Apologies for the mess here. It does sound like something we'd want for 2.13 too. I'll add a note on PR.

**Comment by jamezp** [comment]
Excellent. Thanks for the quick turnaround on this! Should this be closed now since #177 is merged?

**Comment by cowtowncoder** [comment]
Yes, forgot to close.

**Comment by cowtowncoder** [comment]
Probably not quite around the corner: hoping to finalize 2.14 soon but it'll take a while.
And 2.13.3 just got out so there's not much need for immediate 2.13.4.
