### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [FasterXML/jackson-modules-base#18]
Hi

All java source files are without license headers.

Please, confirm the licensing of code and/or content/s, and add license headers

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

This is currently blocking the import of these libraries in Fedora [1]

Thanks in advance

Regards

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1369224

**Comment by puntogil** [comment]
http://www.apache.org/legal/src-headers.html

**Comment by puntogil** [comment]
Hi, Any news here?

**Comment by cowtowncoder** [comment]
@puntogil I thought I have made it clear that we are not going to add license headers into source files. So there will be no progress. If you absolutely must have headers, I would suggest post-processing of packaged sources.

**Comment by puntogil** [comment]
As i wrote in jackson-datatypes-collections/issues/10 for me is clear.
but for the reviewer of https://bugzilla.redhat.com/show_bug.cgi?id=1369224
it is not understandable
Regards and sorry for the noise

**Comment by akurtakov** [comment]
@cowtowncoder Please understand we need clearance. Which is as simple as what you did in jackson-datatypes-collections aka : 
"our policy is not to add license boilerplate in source files.
It serves no useful purpose to us, so we have no intention of adding such headers.

License information is however included in Maven definitions (parent pom.xml), source repositories, and artifacts (via src/main/resources). Git repo wikis also include license information." 
Or even simpler "All content of this git repo is under ASL 2.0 and we don't plan adding license headers." and close the issue but we need this statement written somewhere from the project developers to continue with the import. It's not much effort but we need it once for all projects build at once (usually once per git repo).  Please bare with us and let's move on.

**Comment by cowtowncoder** [comment]
@akurtakov Ah ok sorry. Completely misunderstood. Thank you for clarification.

To whoever it concerns: policy of the Jackson project is to only include licensing information as project level metadata (in repo, pom.xml, artifact within source and binary jars), and not as headers in source files.

Licensing is Apache License 2.0, for Jackson 2.x as indicated by various artifacts, and we have no plans to change this.
