### ISSUE TITLE
Remove stack trace from Blackbirds warnings wrt missing `MethodHandles.lookup()` (on Java 8)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-modules-base#187]
(request by @darxriggs)

"It's a bit disturbing to see a stack trace in normal operation when Blackbird is used with Java 8 for example.

Do you think removing the exception with its stacktrace from the log message is an option?"

----------

This seems reasonable to me, will check with @stevenschlansker .

Code in question is in `ReflectionHack` line 44 or so; would just log but without stack trace.

**Comment by stevenschlansker** [comment]
The reason the exception was logged in the first place was to help diagnose problems with oddball JVMs - "I ran this on IBM JDK and it didn't work right!"
We could remove it, or alternately reduce the level to TRACE level so it is available but hidden by default.

One word of caution, if you do run Java 8, then Blackbird is probably not performing very well. It is best to update your Java version to get actually good performance with Blackbird :)

**Comment by cowtowncoder** [comment]
Thank you @stevenschlansker I think the idea of hiding (but not removing) exception stack trace makes sense. Will get in 2.14.0 release as one of very last things. :)
