### ISSUE TITLE
Missing licenses in older versions

### ISSUE THREAD

**Issue by Hummel83** [FasterXML/jackson-modules-base#202]
In the old versions under 2.12 the license files are missing. Would it be possible to add them?

**Comment by cowtowncoder** [comment]
Technically possible but I don't think it's worth the effort because no new releases are planned.
Full minor releases take 3-4 hours; and for sole purpose of adding license files it wouldn't be worth using my limited time.

**Comment by Hummel83** [comment]
Thank you for the quick reply. I didn't know it was such a pain to update an old version. I will try to use a newer version. 
(We are currently using an old version in an app and my legal department has a problem with libraries without licence terms).

**Comment by cowtowncoder** [comment]
@Hummel83 yeah, it's not the update, it's the release process: old versions in Maven are immutable so one must release new versions. There will be a new 2.14 version; possibly 2.13 even. But 2.12 probably not.
