### ISSUE TITLE
(mrbean) materialized beans duplicate properties by prefixing an underscore

### ISSUE THREAD

**Issue by rethwischk** [FasterXML/jackson-modules-base#21]
The issue documented as fixed at https://github.com/fasterxml/jackson-module-mrbean/issues/20 remains a problem in MrBean 2.7.4. It doesn't occur just during serialization. Any materialized bean appears to have duplicated properties, even when not used for serialization. If we have this

```java
interface A {
  String a;
  int b;
}
```

the following materialized object will be seen in a debugger.

```java
{
  String a;
  int b;
  String _a;
  int _b;
}
```

**Comment by cowtowncoder** [comment]
@rethwischk Code does not prepend `_` any more, so I don't see how this could happen. Are you 100% sure there is no possibility of having an older version in the classpath?

At this point I would need a reproduction of some kind as I can not reproduce the problem you are seeing.

**Comment by rethwischk** [comment]
Thanks. I'll investigate and open another issue if the problem remains.
