### ISSUE TITLE
`JaxbAnnotationIntrospector` should honor the package level annotation `@XmlSchema`

### ISSUE THREAD

**Issue by iiliev2** [FasterXML/jackson-modules-base#218]
https://github.com/FasterXML/jackson-modules-base/blame/758b7004e63b5600853143b0d5586911e50b2dbf/jaxb/src/main/java/com/fasterxml/jackson/module/jaxb/JaxbAnnotationIntrospector.java#L221

Even though it is a root element, it might have a default namespaced defined at the package level. JAXB would serialize such root elements with a namespace, even if the `@XmlRootElement` annotation does not specify a namespace.

See also https://stackoverflow.com/questions/17789157/xjc-doesnt-generate-the-xmlelement-with-namespace

**Comment by cowtowncoder** [comment]
Jackson does not support use of package-level annotations with its annotation support (does not compose well with inheritance-based handling), so this is a fundamental limitation.
What is supported is essentially mapping of JAXB annotations into handling Jackson does support.

So this is not and will not be supported.

**Comment by iiliev2** [comment]
> Jackson does not support use of package-level annotations
> So this is not and will not be supported.
This issue is about one particular behavior in the serializer. How would that be incompatible with the `inheritance-based handling`? What does that mean?

This makes me doubt the usefulness of this module. Often old projects would start schema-first and the annotated classes(and packages) would be auto generated, so they can't be modified by hand. Even if they start code-first, it would defeat the purpose of this module if one would still have to fiddle with the annotations in order to make them produce the same output as with JAXB.

At the very least, these limitations should be documented in more detail.

**Comment by cowtowncoder** [comment]
PRs welcome for doc changes too.

But the main thing to keep in mind is that Jackson is not -- and never meant to be or advertised as -- a JAXB implementation.
It allows annotation-level interoperability that allows translating simple cases like property renaming. But it does not try to emulate semantics in cases where they differ (often due to JAXB. being XML-specific and Jackson JSON-centric).

**Comment by WannabeSoftwareEngineer** [comment]
Apologies in advance if it is not appropriate to comment on a closed issue and it would have been better to open a different thread.

I am also looking in a case where we have the following

```
package com.company.serialization;

@XmlRootElement(name = "TestName")
public class TestObject {
    @XmlElement(name = "TestField")
    protected String field;

    public String getField() {
        return this.field;
    }

    public void setField(String field) {
        this.field = field;
    }
}
```

and we have a package-info.java defined as 

```
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.testing-schema.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.company.serialization;
```

According to the @XmlRootElement java doc, https://docs.oracle.com/javase/8/docs/api/javax/xml/bind/annotation/XmlRootElement.html, when the namespace is not explicitly defined, then the namespace is derived from an @XmlSchema annotation defined in the package of the class.
I understand that Jackson isn't intended as a full replacement for JAXB, but I would like to understand more about the implications of adding support specifically for @XmlSchema.

I noticed that in JaxbAnnotationIntrospector#findAnnotation, we can check the package of a class to locate an annotation. Are there any major downsides to also checking the package for the namespace when it’s not defined directly in the class?

**Comment by cowtowncoder** [comment]
The main problem is that Jackson annotation processing is designed in a way that makes it hard to figure out how package-level annotations should be merged. That's conceptually the biggest problem: in Jackson, annotations inherit via class hierarchy.

But although I have concerns about support (and won't have time or interest to work on it myself), if anyone else had time and itch to see if opt-in support could be added -- possibly just for `@XmlSchema` -- I could help get PR through.
(note: just for JAXB annotation module and NOT for jackson-databind in general)
