### ISSUE TITLE
Afterburner in 3.0 fails to handle interface "default" methods

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-modules-base#226]
Looks like cases 2.x Afterburner (with Asm) handles correctly are failing with 3.0 (ByteBuddy) for some reason:

* tools.jackson.module.afterburner.failing.DefaultMethodsTest
* tools.jackson.module.afterburner.failing.DefaultMethods223Test

Not sure when former started failing (latter was just added) but would be good to resolve.

**Comment by cowtowncoder** [comment]
@geoand Sorry to bug you but I only now realized these failures. Looks like there's an NPE due to `beanClassDescription` passed to callback. But I am not sure how and why this occurs. I was wondering if you remember enough about implementation to help.

Note that since test are under `failing/` they are not run by default (to prevent CI fails); can be run from IDE.
I'd be happy to help too however I can -- this is not critical being for 3.0.0 per se, but would be nice to resolve of course.

**Comment by geoand** [comment]
@cowtowncoder no problem!

Unfortunately I don't remember much, it's been a while 😁.

I can have a look in a few weeks however - sorry I can't look sooner, as there is something work related that we really want to get out the door as soon as possible

**Comment by cowtowncoder** [comment]
@geoand No hurry; anything you can do is an added bonus. I know how busy things are & appreciate your help with your main project :)

**Comment by geoand** [comment]
Sorry I have not been able to look at this yet. Hopefully I can start looking next week.

**Comment by cowtowncoder** [comment]
No problem @geoand -- whenever you have time!

**Comment by geoand** [comment]
@cowtowncoder sorry it took so long to get to this.

#236 should take care of it. 

You'll notice there is a duplication of the traversal algorithm, which I guess we could put somewhere common, I just don't know where :)

**Comment by cowtowncoder** [comment]
Excellent, thank you for following up on this @geoand !

For now, duplication probably best remain as-is; I'll move failing test as they pass & update release notes.

**Comment by cowtowncoder** [comment]
Fixed by #236, closing.

**Comment by geoand** [comment]
🙏
