### ISSUE TITLE
Remove `jackson-module-paranamer` from Jackson 3.0

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-modules-base#40]
Since Jackson 3.0 requires Java 8 as baseline and includes "parameter name" functionality in core databind, there is no more need for Paranamer module. So let's just remove it.

**Comment by iemejia** [comment]
Why was this one closed @cowtowncoder ? After reading the [release notes for Jackson 2.9](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9) I have the impression we could go ahead with it no?

```
No changes from 2.8: Java 7 features available for all modules (meaning, need to compile on Java 7), JDK/JVM 7 is the baseline, except:

    jackson-annotations, jackson-core (streaming) and jackson-jr still only require JDK/JVM 6
    Java 8 modules, Kotlin, Scala module require JDK/JVM 8
```

Or am I missing something?

**Comment by cowtowncoder** [comment]
@iemejia Module was commented out from `pom.xml` and so will not be built for 3.0. Source code may remain there for now just for convenience (no merge conflicts for 2.x -> master).
So it was removed essentially.

**Comment by iemejia** [comment]
I see so there is no way this gets into 2.x at least for the scala modules who are already Java 8 only?

**Comment by cowtowncoder** [comment]
@iemejia I am not sure what your question here is. This issue is about removing a specific module.

Are you asking about something else, like inclusion of parameter name discovery? That will remain separate module for Jackson 2.x, but with 3.0 will be (has been) merge into databind, as it can use Java 8 features.

**Comment by iemejia** [comment]
Yes it is slightly different, maybe I was not clear above. We still package paranamer which is mostly used to cover missing functionality of Java 7 that is now fully covered by Java 8. 
Like jackson 2.9 became Java 8 only (if I interpreted correctly the message in the release notes copied above) we could get rid of paranamer for the next releases of the 2.x branch, can't we?
My goal is to get rid of that pesky little extra dep in multiple projects downstream, and I think it is already possible. WDYT?

**Comment by cowtowncoder** [comment]
Paranamer module is not needed if `jackson-module-parameter-names` -- which uses parameter names from Java 8 byte code (... if available) -- is registered. This wrt every other module, except for Scala. But Scala module might have its own direct dependency on Paranamer; this is not related to module(s) here.
