### ISSUE TITLE
Add missing release notes for 2.9.0 through 2.9.4 in https://github.com/FasterXML/jackson-modules-base/blob/master/jaxb/release-notes/VERSION

### ISSUE THREAD

**Issue by garydgregory** [FasterXML/jackson-modules-base#41]
Add missing release notes for 2.9.0 through 2.9.4 in https://github.com/FasterXML/jackson-modules-base/blob/master/jaxb/release-notes/VERSION

**Comment by cowtowncoder** [comment]
Release notes were moved one level up, so have a look at `.../jackson-modules-base/blob/master/release-notes/VERSION`
