### ISSUE TITLE
Jackson interpretation of XMLElements not compatible with JAXB

### ISSUE THREAD

**Issue by shravass** [FasterXML/jackson-modules-base#48]
I would like to know if issue -> https://github.com/FasterXML/jackson-module-jaxb-annotations/issues/51 was fully resolved.

I am using version 2.9 of jackson-dataformat-xml but still I get the same exception.

**Comment by cowtowncoder** [comment]
@shravass This is not a mailing list for asking questions. If you have comment, add comment there; if reproduction for problem, file a new issue explaining remaining problem.
