### ISSUE TITLE
XML: Different class configurations required for marhalling/unmarshalling of collections

### ISSUE THREAD

**Issue by ewirch** [FasterXML/jackson-modules-base#56]
See this test class:
```
import static java.util.Arrays.asList;
import static org.junit.Assert.assertEquals;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.dataformat.xml.JacksonXmlModule;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import org.junit.Before;
import org.junit.Test;

import java.beans.ConstructorProperties;
import java.io.IOException;
import java.util.Collection;

public class CollectionMarshalling {

    private static final String XML = "<root><names><name>name1</name><name>name2</name></names></root>";

    private XmlMapper xmlMapper;

    @Before
    public void setUp() {
        xmlMapper = new XmlMapper(new JacksonXmlModule());
    }

    @Test
    public void testMarshallingWithoutWrapper() throws JsonProcessingException {
        assertEquals(
            "<root><names><name>name1</name><name>name2</name></names></root>",
            xmlMapper.writeValueAsString(new RootWithoutWrapper(asList("name1", "name2")))
        );
    }

    @Test
    public void testMarshallingWithWrapper() throws JsonProcessingException {
        assertEquals(
            XML,
            xmlMapper.writeValueAsString(new RootWithWrapper(asList("name1", "name2")))
        );
    }

    @Test
    public void testUnmarshallingWithoutWrapper() throws IOException {
        assertEquals(
            asList("name1", "name2"),
            xmlMapper.readValue(XML, RootWithoutWrapper.class).names
        );
    }

    @Test
    public void testUnmarshallingWithWrapper() throws IOException {
        assertEquals(
            asList("name1", "name2"),
            xmlMapper.readValue(XML, RootWithWrapper.class).names
        );
    }

    @JacksonXmlRootElement(localName = "root")
    public static class RootWithoutWrapper {
        @JacksonXmlProperty
        Collection<String> names;

        @ConstructorProperties({"names"})
        public RootWithoutWrapper(Collection<String> names) {
            this.names = names;
        }
    }

    @JacksonXmlRootElement(localName = "root")
    public static class RootWithWrapper {
        @JacksonXmlElementWrapper(localName = "names")
        @JacksonXmlProperty(localName = "name")
        Collection<String> names;

        @ConstructorProperties({"names"})
        public RootWithWrapper(Collection<String> names) {
            this.names = names;
        }
    }

}
```

This is the test result:
* `testMarshallingWithoutWrapper`: FAILED
* `testMarshallingWithWrapper`: SUCCESS
* `testUnmarshallingWithWrapper`: ERROR
* `testUnmarshallingWithoutWrapper`: SUCCESS

You see, if I want to unmarshall XML I *must not* use `@JacksonXmlElementWrapper`. If I want to marshall I *have to* use `@JacksonXmlElementWrapper`. This impossible with one class.

**Comment by cowtowncoder** [comment]
This is a case where use of mix-in annotations probably makes sense, or alternatively custom `AnnotationIntrospector`. Either way you will need 2 separate `XmlMapper`s with differing configuration, but can vary behavior.

**Comment by ewirch** [comment]
I don't understand why I would need two different `XmlMapper` configurations to correctly marshall/unmarshall XML? There should be (at least) one valid configuration, which will read XML of one kind and also write the same XML format. I expect either:

* testMarshallingWithoutWrapper: SUCCESS
* testUnmarshallingWithoutWrapper: SUCCESS

OR:

* testMarshallingWithWrapper: SUCCESS
* testUnmarshallingWithWrapper: SUCCESS

**Comment by cowtowncoder** [comment]
I answered the question wrt "how can I make serialization/deserialization work differently".

If the problem is with specific incompatibility between what Jackson writes, and then reading it back in, that's different question. Jackson does indeed try to support this level of round-tripping.
What is not supported are various ways of using different POJOs or configurations and make those work both ways.

But if so, I assume you would point out which part you think is working incorrectly to prevent things working. Unit tests are good at reproducing problems, but not always good way of describing them.

**Comment by ewirch** [comment]
You're right, description could have been clearer. I'm looking for one working configuration which can be used for serialzation and deserialization. Is the issue clear now?

**Comment by cowtowncoder** [comment]
As per earlier comments, it does not seem like there is a single configuration, but rather two mappers may be needed (possibly with mix-in annotations).
