### ISSUE TITLE
[guice] ObjectMapperModule doesn't allow configuring JsonFactory to use

### ISSUE THREAD

**Issue by bogdan-neoworks** [FasterXML/jackson-modules-base#6]
Hi,

ObjectMapperProvider, the static private class, used by ObjectMapperModule inside, is doing internally among other stuff:
final ObjectMapper mapper = new ObjectMapper();
which doesn't allow us to inject a JsonFactory into into the mapper, 
e.g. new ObjectMapper(MongoBsonFactory.createFactory()), like it would be needed in case of using jongo for example.

Can you solve this issue, please?

Thank you,
Bogdan

**Comment by bogdan-neoworks** [comment]
Btw, I can do that, I can make it parametrizable, and create a pull request so you can take a look and let me know what you think.

**Comment by cowtowncoder** [comment]
@bogdan-neoworks Is this for Guice module? If so, it would be nice to include that in title (I'll do that).

PR would make sense; I am not very familiar with Guice module as it was a contribution, so I assume what you are asking for makes sense.

**Comment by bogdan-neoworks** [comment]
Hi @cowtowncoder , that is correct, I am talking about the GuiceModule. ObjectMapper has a constructor which can take as a parameter JsonFactory (in my case it would be a BsonFactory, a json factory MongoDB). It would be nice if we could get the same flavor of variety in terms of json factories, when we use ObjectMapperModule.

Thanks!

**Comment by cowtowncoder** [comment]
Gotcha. Sounds reasonable to me.

**Comment by bogdan-neoworks** [comment]
Hey cowtowncoder, I have a quick one for you. Based on your expertise, what options do I have if I want to inject into a Jackson Entity (the result of unmarshalling jsons) a Service or any other component? @JsonSerializer on a field, @JacksonInject, guice module,.... 

Appreciate it!

**Comment by cowtowncoder** [comment]
@bogdan-neoworks This is a good question for mailing lists. All options you mention should be available, although I have only used `@JacksonInject`. OSGi module uses injection framework as well as guice module, and it should be quite easy to write your own if you need different source for injected stuff.
Another feature that may help would be "context attributes", `DeserializationContext` has `getAttribute()` (and `setAttribute()`) that allows a place to stash some settings that are accessible for deserialization.

**Comment by cowtowncoder** [comment]
At this point I am not 100% sure how this request should work; I assume it'd be one more constructor for module, to take `ObjectMapper`, and probably than hold on to that version instead of constructing new one... but since I don't use Guice, nor know how to test, it's probably best to send PR or add snippets here.

**Comment by bogdan-neoworks** [comment]
Hi cottowncoder, one more constructor for the module is exactly what I had in my mind. 
Sorry for replying so late.

**Comment by bogdan-neoworks** [comment]
I did the change I requested locally(adding a constructor), but I noticed that inside GuiceInjectableValues, when doing: 
return `injector.getInstance((Key) valueId)` it's failing horribly by saying that: "can not cast a String com.somepackage.Service" into a Key.
So can you do the change please, because maybe I am missing something obvious and I can test it and let you know if it works or not.

Thanks cowtowncoder.

**Comment by bogdan-neoworks** [comment]
I tried to push a new created branch but I don't think to I am able to do push anything.

**Comment by bogdan-neoworks** [comment]
I can confirm this is a fully working version:
```
public class ObjectMapperModule implements com.google.inject.Module
{
  private final List<Module> modulesToAdd = new ArrayList<Module>();
  private final List<Key<? extends Module>> modulesToInject = new ArrayList<Key<? extends Module>>();
  private final Key<ObjectMapper> objectMapperKey;
  private  ObjectMapper objectMapper = new ObjectMapper();

  private Class<? extends Annotation> scope = null;

  public ObjectMapperModule()
  {
    this(Key.get(ObjectMapper.class));
  }

  public ObjectMapperModule(Class<? extends Annotation> annotation)
  {
    this(Key.get(ObjectMapper.class, annotation));
  }

  public ObjectMapperModule(Annotation annotation)
  {
    this(Key.get(ObjectMapper.class, annotation));
  }

  public ObjectMapperModule(Key<ObjectMapper> objectMapperKey)
  {
    this.objectMapperKey = objectMapperKey;
  }

  public ObjectMapperModule in(Class<? extends Annotation> scopeAnnotation)
  {
    scope = scopeAnnotation;
    return this;
  }

  public ObjectMapperModule registerModule(Module module)
  {
    modulesToAdd.add(module);
    return this;
  }

  public ObjectMapperModule registerModule(Class<? extends Module> clazz)
  {
    return registerModule(Key.get(clazz));
  }

  public ObjectMapperModule registerModule(Class<? extends Module> clazz, Class<? extends Annotation> annotation)
  {
    return registerModule(Key.get(clazz, annotation));
  }

  public ObjectMapperModule registerModule(Class<? extends Module> clazz, Annotation annotation)
  {
    return registerModule(Key.get(clazz, annotation));
  }

  public ObjectMapperModule withObjectMapper(ObjectMapper objectMapper)
  {
    this.objectMapper = objectMapper;
    return this;
  }

  public ObjectMapperModule registerModule(Key<? extends Module> key)
  {
    modulesToInject.add(key);
    return this;
  }

  @Override
  public void configure(Binder binder)
  {
    final ScopedBindingBuilder builder = binder.bind(objectMapperKey)
                                               .toProvider(new ObjectMapperProvider(modulesToInject, modulesToAdd, objectMapper));

    if (scope != null) {
      builder.in(scope);
    }
  }

  private static class ObjectMapperProvider implements Provider<ObjectMapper>
  {
    private final List<Key<? extends Module>> modulesToInject;
    private final List<Module> modulesToAdd;

    private final List<Provider<? extends Module>> providedModules;
    private Injector injector;
    private final ObjectMapper objectMapper;

    public ObjectMapperProvider(List<Key<? extends Module>> modulesToInject,
                                List<Module> modulesToAdd,
                                ObjectMapper objectMapper)
    {
      this.modulesToInject = modulesToInject;
      this.modulesToAdd = modulesToAdd;
      this.objectMapper = objectMapper;

      this.providedModules = new ArrayList<Provider<? extends Module>>();
    }

    @Inject
    public void configure(Injector injector) {
      this.injector = injector;
      for (Key<? extends Module> key : modulesToInject) {
        providedModules.add(injector.getProvider(key));
      }
    }

    @Override
    public ObjectMapper get()
    {
      final ObjectMapper mapper = objectMapper.copy();
      mapper.registerModules(modulesToAdd);
      for (Provider<? extends Module> provider : providedModules) {
        mapper.registerModule(provider.get());
      }

      final GuiceAnnotationIntrospector guiceIntrospector = new GuiceAnnotationIntrospector();
      mapper.setInjectableValues(new GuiceInjectableValues(injector));
      mapper.setAnnotationIntrospectors(
          new AnnotationIntrospectorPair(
              guiceIntrospector, mapper.getSerializationConfig().getAnnotationIntrospector()
          ),
          new AnnotationIntrospectorPair(
              guiceIntrospector, mapper.getDeserializationConfig().getAnnotationIntrospector()
          )
      );
      return mapper;
    }
  }
}
```

**Comment by bogdan-neoworks** [comment]
Hi cowtowncoder,

Can you please do the change above, around the ObjectMapperModule?
I am using this in production as we speak and it is working very fine.

Appreciate it,
Bogdan

**Comment by cowtowncoder** [comment]
@bogdan-neoworks here goes; added in `master` for 2.8.0. Please let me know if/that it works.

One thing I was wondering about was the `copy()` for mapper; I assume it may be necessary if injection are for non-singleton mappers? I left that in there, was just wondering if it is necessary or not.
