### ISSUE TITLE
What is new in new version with afterburner?

### ISSUE THREAD

**Issue by q294881866** [FasterXML/jackson-modules-base#64]
In my project we use default jackson-module-afterburner  version is 2.8.10, but somebody use version for 2.9.5 .
My question is how different with new version？
I dont found any useful information in docs, Thanks a lot.

**Comment by cowtowncoder** [comment]
Feature-wise there isn't anything new, but you do need to make sure that minor versions of Afterburner module and `jackson-databind` match; compatibility across minor versions is not guaranteed between components (unlike compatibility of public external API exposed by Jackson).

In future, please use mailing lists: issue tracker is not a Q&A forum.

**Comment by q294881866** [comment]
Get it, thank you.
