### ISSUE TITLE
Use @XmlSchemaType hints

### ISSUE THREAD

**Issue by andrei-ivanov** [FasterXML/jackson-modules-base#67]
Hi,
Using an XmlJavaTypeAdapter to convert types works fine when serializing to XML.
The problem comes up with JSON serialization and types that are shouldn't really be serialized to `string` when they are actually `boolean` or `number`, as can be seen in an existing [test](https://github.com/FasterXML/jackson-modules-base/blob/master/jaxb/src/test/java/com/fasterxml/jackson/module/jaxb/adapters/TestAdapters.java#L198).

Even though the object is [`long`](https://github.com/FasterXML/jackson-modules-base/blob/master/jaxb/src/test/java/com/fasterxml/jackson/module/jaxb/adapters/TestAdapters.java#L99), it ends up serialized as `string` in JSON.
I'm thinking that the `@XmlSchemaType` hint should help here, if it would be used.

**Comment by andrei-ivanov** [comment]
Well, let me try to give more details about my case then 🙂
I have a `complexType` with a property like this: `<xs:element name="active" type="xs:boolean" />`

Since JAXB generates this as a `boolean` primitive, bean validation can't tell if an XML had the `active` element defined or not, so we tried to force JAXB to generate the `Boolean` wrapper instead.

The way we found to do it was to use an `XmlAdapter`:
```java
public class BooleanAdapter extends XmlAdapter<String, Boolean> {
   @Override
   public Boolean unmarshal(String string) {
      if (string == null) {
         return null;
      }

      return DatatypeConverter.parseBoolean(string.trim());
   }

   @Override
   public String marshal(Boolean aBoolean) {
      if (aBoolean == null) {
         return null;
      }

      return DatatypeConverter.printBoolean(aBoolean);
   }
}
```
The JAXB generated property now looks like this:
```java
@XmlElement(name = "active", required = true, type = String.class)
@XmlJavaTypeAdapter(BooleanAdapter.class)
@XmlSchemaType(name = "boolean")
@NotNull
protected Boolean active;
```

When serializing this to XML, everything is fine, we get something like
```xml
<active>true</active>
```

The problem is with JSON, as that gets serialized as `string` instead of `boolean`:
```json
"active": "true"
```
I was hoping that the information provided in `@XmlSchemaType(name = "boolean")` could be used to generate it properly as
```json
"active": true
```
This way the TypeScript/JavaScript frontend can do proper expressions on this kind (`boolean` and `number`) of fields.

But perhaps I misunderstood what `XmlSchemaType` does 🙁

**Comment by cowtowncoder** [comment]
I don't really quite follow what would be expected here, unfortunately, so not sure what (if anything) could or should be done.
Closing: may be reopened or recreated with specific (failing) unit test to show expected behavior.
