### ISSUE TITLE
2.9 JDK 11 compatablility

### ISSUE THREAD

**Issue by ulrichenslin** [FasterXML/jackson-modules-base#76]
By updating to JDK 11 compatible libs, the build now passes all the tests on JDK 1.7, 1.8 and 11.

See PR : https://github.com/FasterXML/jackson-modules-base/pull/75

The tests are focused on 1.7 and 1.8 environments, and it would not be possible to include JDK 11 specific tests without breaking compatibility with 1.7 and 1.8.

Would it be a fair assumption to make, that if the tests pass while running on JDK 11, that it is JDK 11 compatible?

Are there any known issues with running 2.9 jackson-modules-base on JDK 11?

**Comment by cowtowncoder** [comment]
Thank you for suggesting this. I'll have to take another look at 2.9, tests, it has been a while.

My understanding is that Jackson (core and all "official" modules) works on Java 11, but that there may be some issues regarding accessibility with Afterburner module.
Compared to earlier 2.x versions, 2.9 has been tested occasionally against Java 11, so I would definitely recommend upgrade to it from previous minor versions.

As I mentioned in PR, I updated Asm version for 2.10 branch (for 2.10.0), but am bit hesitant to do the same for 2.9(.9). If there are specific problems I will consider backport, however; please let me know if you know of any.

**Comment by cowtowncoder** [comment]
Looks like tests from `2.9` pass with JDK 11.

**Comment by ulrichenslin** [comment]
@cowtowncoder Thanks again for the feedback.

Pre version 7 AMS was the main concern, since it can cause runtime errors when reading classes compiled to a higher source level.
 
The ASM version in 2.10 will address the ASM issue.

We can close this issue.
