### ISSUE TITLE
Consider making the dep on javax.activation optional

### ISSUE THREAD

**Issue by mbooth101** [FasterXML/jackson-modules-base#77]
Jackson is very careful to determine whether javax.activation is needed without it needing to be on the classpath, as evidenced here:

https://github.com/FasterXML/jackson-modules-base/blob/master/jaxb/src/main/java/com/fasterxml/jackson/module/jaxb/JaxbAnnotationIntrospector.java#L666

So could we make javax.activation optional?

**Comment by mbooth101** [comment]
The change would be trivial, see my PR #78

**Comment by cowtowncoder** [comment]
So... "optional" dependency won't work wrt JDK11 (build fails), but using "provided" does.
I am not 100% sure if there might be runtime issues with module system (if so will need to revisit), but let's try and see.

Thank you for suggesting this!

**Comment by mbooth101** [comment]
Ah, but "provided" does not make the dependency optional in the generated OSGi metadata, which is what I really care about :-)

So in that case, I would like to propose one additional change, to explicitly make it optional by setting the osgi.import property

I have no way of reopening this ticket, but I can submit another PR, see #80
