### ISSUE TITLE
2.10 : Afterburner test error 

### ISSUE THREAD

**Issue by GedMarc** [FasterXML/jackson-modules-base#82]
```
[INFO] Running com.fasterxml.jackson.module.afterburner.ser.TestSimpleSerialize
[ERROR] Tests run: 16, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.003 s <<< FAILURE! - in com.fasterxml.jackson.module.afterburner.ser.TestSimpleSerialize
[ERROR] testGeneratedSerializerName(com.fasterxml.jackson.module.afterburner.ser.TestSimpleSerialize)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoSuchFieldException: classes
        at com.fasterxml.jackson.module.afterburner.ser.TestSimpleSerialize.testGeneratedSerializerName(TestSimpleSerialize.java:221)
```

```

[ERROR] Tests run: 18, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.006 s <<< FAILURE! - in com.fasterxml.jackson.module.afterburner.deser.TestSimpleDeserialize
[ERROR] testGeneratedDeserializerName(com.fasterxml.jackson.module.afterburner.deser.TestSimpleDeserialize)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoSuchFieldException: classes
        at com.fasterxml.jackson.module.afterburner.deser.TestSimpleDeserialize.testGeneratedDeserializerName(TestSimpleDeserialize.java:338)
```

**Comment by cowtowncoder** [comment]
On JDK 11 or... ?

**Comment by GedMarc** [comment]
JDK 12, so very probably - 

Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T21:49:05+02:00)
Maven home: C:\Java\maven\bin\
Java version: 12, vendor: Oracle Corporation
Java home: C:\Java\jdk\jdk-12
Default locale: en_ZA, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

openjdk version "12" 2019-03-19
OpenJDK Runtime Environment (build 12+33)

I actually suspect it's a class exposure thing, I'll take a deeper look into it. 
Been away for a bit sorry, moved house xD

**Comment by GedMarc** [comment]
yeah 

 due to access error (type com.fasterxml.jackson.module.afterburner.TestAccessFallback$BogusTestError, message=boom!)

**Comment by cowtowncoder** [comment]
Congratulations on move! Yeah, new JDKs sometimes add new properties into JDK types, and for some types that breaks tests (or even handling). So need to install JDK 12, javadocs, and see what happens here.

**Comment by GedMarc** [comment]
Hmm date time serializer in jdk 12 as well, no longer accepts null datetimeformatter sigh

![image](https://user-images.githubusercontent.com/5367513/64276351-0c272e00-cf48-11e9-8605-6384eb8087e1.png)

**Comment by GedMarc** [comment]
I've always been sceptical thinking 6 month releases are definitely the way to go - 
but i must admit, i'm starting to get that sour taste in my mouth xD

**Comment by GedMarc** [comment]
oh wait - is this the wrong java 8 library?!?

Caused by: java.lang.NullPointerException: formatter
at java.base/java.util.Objects.requireNonNull(Objects.java:246)
at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:491)
at com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer.deserialize(LocalDateTimeDeserializer.java:92)
at **com.fasterxml.jackson.datatype.jsr310**.deser.LocalDateTimeDeserializer.deserialize(LocalDateTimeDeserializer.java:39)

**Comment by cowtowncoder** [comment]
Yes, you want `JavaTimeModule` instead. Not sure it is different but... I'll add this to my list of things to check when I find time.

**Comment by cowtowncoder** [comment]
Oh wow. Some really fragile in there, attempting to peek into generated method name(s) for (de)serializer. While goal makes sense, the way it was done was fragile so not surprising it might break at some point: here in JDK 12.

I commented out tests; if someone has time and interest in checking how to replace them, feel free to, but for now let's just get rid of said tests.

**Comment by cowtowncoder** [comment]
@GedMarc I fixed the issue wrt Afterburner. But if there is another JDK 12 error wrt Java 8 date/time, could you make sure there's an issue under `jackson-modules-java8` as well for that problem?
