### ISSUE TITLE
Please comply with ASM license when re-distributing ASM 

### ISSUE THREAD

**Issue by vlsi** [FasterXML/jackson-modules-base#83]
ASM license specifies that `Redistributions of source code must retain the ... copyright notice`

I see that `jackson-module-afterburner-2.9.9.jar` bundles ASM under `jackson-module-afterburner-2.9.9.jar/uzip://com/fasterxml/jackson/module/afterburner/asm` path, however it fails to retain the relevant copyright notice.

Would you please comply with ASM license? (see https://gitlab.ow2.org/asm/asm/blob/e246de13a995837bc88777aca47f141d9bcbfc01/LICENSE.txt )

Thanks.

See also:
* https://github.com/raphw/byte-buddy/issues/709
* https://gitlab.ow2.org/asm/asm/issues/317881

**Comment by cowtowncoder** [comment]
We definitely do want to comply with ASM licensing, and deviations are not intentional.
I'll have a look at links to see what would make most sense here.

It is easy to add notes to README/Wiki of project, or add information under  `src/main/resources/META-INF/LICENSE` or `.../NOTICE` (which are missing, compared to other Jackson projects, like `jackson-databind`).
I assume these two places would make sense.

**Comment by vlsi** [comment]
Note: the license requires to include copyright notice **within** binary redistributions.

Project readme/wiki has no relation with `jackson-module-afterburner-2.9.9.jar` that is published to Maven Central

**Comment by cowtowncoder** [comment]
This is why I mentioned second part, as LICENSE and NOTICE do get included in jar/bundle.
But sounds like Wiki part is out of scope.

**Comment by vlsi** [comment]
Adding ASM's license to `META-INF/LICENSE` would be OK.

PS. If you have some time, and if you think https://gitlab.ow2.org/asm/asm/issues/317881 would make your life easier, it would be nice if you add some comments there.

**Comment by cowtowncoder** [comment]
I cut'n pasted ASM License file contents in `LICENSE`, and it will be included in jars for 2.9, 2.10 and 3.0 (master) once new versions built (no releases planned for older branches, although if any made I can easily copy over files if that was to happen for some critical patch).
So, `2.9.10`, `2.10.0` (and distant future `3.0.0`) versions will include license information as expected.
