### ISSUE TITLE
POM: Missing license information

### ISSUE THREAD

**Issue by melloware** [FasterXML/jackson-modules-base#88]
We use Sonatype IQ Server and its reporting all Jackson JARs as missing their license info.  This is a simple fix add this section to your base pom.xml which is inherited by all your JARS.

```xml
	<licenses>
		<license>
			<name>Apache 2</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
			<comments>A business-friendly OSS license</comments>
		</license>
	</licenses>
```

**Sonatype screenshot showing warnings:**
![image](https://user-images.githubusercontent.com/4399574/67975704-fef68a80-fbea-11e9-8b24-ab020871e106.png)

**Comment by cowtowncoder** [comment]
You should probably file a bug issue against Sonatype tooling as license information should be resolved from parent poms that include it, to reduce unnecessary clutter on poms.

Specifically, it's via `jackson-parent`:

https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/

although I could probably duplicate this for `jackson-base` for convenience.

Further note, however, that jars actually also contain license information under `META-INF/LICENSE`.

It is possible that there is something else going on, but I think Sonatype system should already be able to deduce license information.

**Comment by melloware** [comment]
I will report this issue to them.

**Comment by melloware** [comment]
Its the goofy way Sonatype reports license issues.  You are doing exactly the right thing already. Closing ticket.
