### ISSUE TITLE
Please apply the license properly

### ISSUE THREAD

**Issue by enepomnyaschih** [FasterXML/jackson-modules-base#91]
Could you please properly apply Apache 2.0 license boilerplate to all source files of "jaxb-annotations" module as per APPENDIX section in https://github.com/FasterXML/jackson-modules-java8/blob/master/LICENSE? I'll appreciate if you can do this for legacy version 2.9 of the module as well. Thank you.

**Comment by cowtowncoder** [comment]
No.
