### ISSUE TITLE
Does jackson 2.9.5 support for Java 11? If not, any timeline or recommendation?

### ISSUE THREAD

**Issue by xinmin-zhou** [FasterXML/jackson-modules-base#93]
Hi Expert,
I would appreciate if you could share your knowledge related with me? Thanks.

Regards,
Xinmin

**Comment by cowtowncoder** [comment]
Please ask questions either on mailing lists:

* https://groups.google.com/forum/#!forum/jackson-user

or gitter chat

* https://gitter.im/FasterXML/jackson-databind

Issue tracker is for reporting issue, or requesting new features.

If asking, also formulate question clearly: "supports java 11" is a very vague question and it is not clear what exactly is being asked (support how?)
