### ISSUE TITLE
Jaxb module not serializing XmlElementWrapper correctly

### ISSUE THREAD

**Issue by TroyMass** [FasterXML/jackson-modules-base#98]
When the model being serialized contains a field like this:
```
    @XmlElementWrapper( name = "identifiers" )
    @XmlElement( name = "identifier" )
    @JsonProperty(value = "identifiers")
    List<Identifier> identifiers;
```
The field name when serialized as JSON is coming out as `identifier` instead of `identifiers`.

It looks like the jaxb module is preferring the jaxb annotations over the json ones like the [documentation](https://github.com/FasterXML/jackson-modules-base/tree/master/jaxb) says, however it doesn't seem to be reading the XmlElementWrapper annotation. The documentation says that it can be configured to prefer the json annotations but it does not show an example of this configuration.

**Comment by cowtowncoder** [comment]
README should be updated to explain this better: tiny example on using `Pair` shows how to combine Jackson and JAXB annotation introspectors (as JAXB one does not handle Jackson annotations at all, literally), wherein first introspector has precedence over second one.
So ordering matters: to have JAXB take precedence, it should be first, Jackson one second.

You can try to see if that makes a difference. The other part, however, is whether wrapper name is used at all with json: I don't remember what logic was used there (this is bit tricky question as it is sort of meaningless in JSON case; but may make sense when trying to keep XML and JSON models as consistent as possible).

**Comment by TroyMass** [comment]
It looks like there is a configuration setting in the object mapper to change the behavior. `objectMapper.enable( MapperFeature.USE_WRAPPER_NAME_AS_PROPERTY_NAME );`

**Comment by cowtowncoder** [comment]
I think that setting works to resolve the issue, closing.
